version: '2.4'

services:
  rsyslog:
    container_name: rsyslog
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./logs:/var/log
    ports:
      - 514:514/tcp
      - 514:514/udp
